version: "3.8"

services:
  dashboard:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data_distribuidor:/app/data_distribuidor
      - ./data_generacion:/app/data_generacion
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
